tailscale/tailscale-client-go

- .github/workflows/ci.yml
This commit modifies the CI workflow to only run when pushed to master or on
pull requests. This avoids the CI running twice when a pull request is opened/synced.
> Modify GitHub actions workflow to reduce redundant runs

- README.md
- tailscale/client.go
- tailscale/client_test.go
Added support for deleting devices using the go client. Needed as I want to add support for removing devices in the terraform provider as another user requested [here](https://github.com/davidsbond/terraform-provider-tailscale/issues/68)
This commit adds the capability of deleting devices based on their IDs.
> Implements the device delete endpoint

- tailscale/client.go
- tailscale/client_test.go
Closes #5
This commit adds the `Data` field to the `APIError` type and provides a helper function `ErrorData` to obtain
the slice of errors from the response. This will allow us to expose errors in ACL tests.
> Add Data field to api errors

- tailscale/client.go
- tailscale/client_test.go
Closes #7
This commit adds the `SetDeviceKey` method to the `Client` type which can be used to configure the
properties of a device key.
> Add SetDeviceKey method to client

- tailscale/client.go
- tailscale/client_test.go
This commit adds the `KeyExpiryDisabled` boolean field to the `Device` type. This field indicates that a device
key has been configured to never expire.
This field is required for https://github.com/davidsbond/terraform-provider-tailscale/issues/78 on the terraform
provider so that we can perform a read on the device to determine the existing properties of a device key.
> Add KeyExpiryDisabled field to Device

- tailscale/client.go
- tailscale/client_test.go
First of all, thank you so much for developing the handy library!
This PR adds some exported fields to the `Device` type. It will allow us to collect device-related metrics and manage devices using this client library. Several use-cases in my mind are:
- Collect `ClientVersion` to warn those who use an outdated client.
- Collect `LastSeen` to delete a device not seen in the past N days.
> Expose more fields on Device

- tailscale/client.go
This commit adds the source, destination and protocol fields for ACLs which are the intended
replacement for users and ports.
Related to https://github.com/davidsbond/terraform-provider-tailscale/issues/89
> Add new policy syntax fields to ACL

- tailscale/client.go
- tailscale/client_test.go
This field does not exist and causes errors when posting an ACL.
> Remove destination field from ACLTest type

- tailscale/client.go
- tailscale/client_test.go
- tailscale/maybe_empty_time_test.go
- tailscale/testdata/devices.json
- tailscale/time_test.go
The Tailscale API returns blank strings for non-existing timestamps, such as the "created" timestamp for Tailscale managed devices. One example is the "hello" device that is returned in the [get devices endpoint](https://github.com/tailscale/tailscale/blob/main/api.md#tailnet-devices-get). 
This will introduce a new struct called `MaybeEmptyTime` which wraps stdlib's `time.Time` struct and is able to Unmarshal Tailscale's representation of a missing timestamp.
> fix: allow for parsing json parsing when timestamps are empty

- tailscale/client.go
- tailscale/client_test.go
This commit moves the Preauthorized field from the device key to the tailnet
key. This was originally a mistake in the tailscale documentation, the field
would have never worked on the device key.
Related to https://github.com/davidsbond/terraform-provider-tailscale/issues/111
> Move preauthorized to tailnet key

- tailscale/client.go
- tailscale/tailscale_test.go
Related to https://github.com/davidsbond/terraform-provider-tailscale/issues/113
This commit modifies the request making code to not attempt to standardise
response bodies if we are not attempting to parse the response. For example, the
tailnet key delete API response has an empty body, which would cause errors when
calling hujson.Standardize.
> Do not attempt to standardise response bodies when we don't need to

- tailscale/client.go
- tailscale/client_test.go
- tailscale/testdata/acl.hujson
- tailscale/testdata/acl.json
- tailscale/time_test.go
This commit adds the `ssh` section to the ACL type, allowing users of
the package to specify their SSH configuration for the Tailscale SSH
feature:
https://tailscale.com/blog/tailscale-ssh/
> Add support for Tailscale SSH

- tailscale/client.go
- tailscale/client_test.go
This commit adds a `ValidateACL` method to the `Client` type that will be used to check the ACL is well formatted and the specified tests pass. It uses the JSON object method described in the API documentation.
This will be required for implementing additional validation as requested on the terraform provider:
https://github.com/tailscale/terraform-provider-tailscale/issues/158
> Add method for ACL validation

- .github/workflows/ci.yml
This commit modifies the actions workflow to trigger for the `main` branch. It was previously using `master` but has since been updated.
> Run CI on main branch

- README.md
- tailscale/client.go
- tailscale/client_test.go
Closes #28
This commit adds the `Client.Keys` method that will return a list of all active keys within the tailnet for the user who owns the API key.
> Add method for listing keys

- tailscale/client.go
- tailscale/client_test.go
Need key expiry in the terraform provider, and I saw it was not yet added to the client pkg, but is available in the API. 
Will open separate PR for terraform provider, if this is approved.
Thanks!
> add expiry to key capabilities

- tailscale/client.go
- tailscale/client_test.go
Fixes: #35 
Signed-off-by: Johan Siebens <johan.siebens@gmail.com>
> client: add options to configure create key request, e.g. with expiry

- tailscale/client.go
- tailscale/client_test.go
- tailscale/tailscale_test.go
This adds a `WithETag` option that allows specifying an ETag value while writing ACL contents.
Also, a few missing ACL file fields have been added based on https://tailscale.com/kb/1018/acls/
Updates tailscale/terraform-provider-tailscale#182
Signed-off-by: Anton Tolchanov <anton@tailscale.com>
> Allow specifying ETag value while setting ACLs

- tailscale/client.go
- tailscale/client_test.go
- tailscale/time_test.go
This should avoid meaningless diffs and unnecessary empty values while managing ACL contents via Terraform.
Fixes #31
Signed-off-by: Anton Tolchanov <anton@tailscale.com>
> Avoid serializing empty ACL fields

- tailscale/client.go
- tailscale/client_test.go
The `Key` type is missing the `Description` property, this PR adds it in.
> Add `Description` property to `Key`

- tailscale/client.go
- tailscale/client_test.go
- Add support for the value of `false` in the `/authorized` endpoint.
- Update the ACL schema with some recently introduced fields.
> tailscale: add recently introduced fields

- tailscale/client.go
tagOwners and autoApprovers are incorrectly serializing all lowercase, which is causing an inconsistency on the terraform provider: the terraform plan always show a diff between what is previously deployed (camelcase 'tagOwners' and 'autoApprovers') and the new plan (all lowercase 'tagowners' and 'autoapprovers'), regardless of whether those attributes were changed or not.
> Fix incorrect case of tagOwners and autoApprovers

- tailscale/client.go
Updates tailscale/terraform-provider-tailscale#144
> tailscale: add missing fields for the auth/api keys

- tailscale/client.go
- tailscale/client_test.go
Support the GET/PATCH/PUT `/api/v2/tailnet/{tailnetID}/dns/split-dns` endpoints for reading, updating, and replacing split DNS settings for a given tailnet respectively.
Updates https://github.com/tailscale/corp/issues/19483
> tailscale: support split DNS endpoints

- tailscale/client.go
- tailscale/client_test.go
https://github.com/tailscale/tailscale/blob/main/api.md#set-device-ipv4-address
> tailscale: support set device ipv4 address

- tailscale/client.go
- tailscale/client_test.go
Support contacts endpoints in the client.
Updates https://github.com/tailscale/corp/issues/21631
> tailscale: support contacts endpoints

- README.md
- v2/client.go
- v2/client_test.go
- v2/go.mod
- v2/go.sum
- v2/tailscale_test.go
This implementation will allow us to organize the various portions of the client into separate resources.
We will add these resources one by one.
> v2: added skeleton of v2 client

- v2/client.go
- v2/devices.go
- v2/devices_test.go
- v2/testdata/devices.json
Depends on https://github.com/tailscale/tailscale-client-go/pull/89
> v2: added support for DevicesResource

- v2/client.go
- v2/devices.go
- v2/webhooks.go
- v2/webhooks_test.go
> v2: added WebhooksResource

- v2/client.go
- v2/client_test.go
Adds unit test to test URL building.
> v2: correctly URL encode tailnet in buildTailnetURL

- v2/client.go
- v2/client_test.go
- v2/contacts.go
- v2/contacts_test.go
- v2/devices.go
- v2/devices_test.go
- v2/tailscale_test.go
- v2/testdata/devices.json
- v2/webhooks.go
- v2/webhooks_test.go
Some consumers of this SDK, for example terraform-provider-tailscale, use other packages named 'tailscale'. To avoid having to alias when importing this package, rename to 'tsclient' to avoid most collisions by default.
> v2: rename package from tailscale -> tsclient

- v2/client.go
- v2/logging.go
- v2/logging_test.go
Support logstream configuration endpoints in the client.
Updates https://github.com/tailscale/corp/issues/21623
> tailscale: support logstream configuration endpoints

- v2/device_posture.go
- v2/device_posture_test.go
Allows getting a single device posture integration by id.
Updates tailscale/corp#21624
> v2: add DevicePostureResource.GetIntegration

- README.md
- v2/client.go
- v2/dns.go
- v2/dns_test.go
Since SplitDNSResponse is already a map, it's possible to return nil without using a pointer.
This also renames SplitDnsResponse -> SplitDNSResponse to keep with Go casing conventions.
> v2: return base SplitDNSResponse instead of pointer

- README.md
This adds an overview of the version options to
https://github.com/tailscale/tailscale-client-go
It removes the v1 example (it's in the godoc if people want it), lists
v2 first, put provides godoc to both.
This is the information I look for first when looking at a GitHub
README for a Go project.
> README: deemphasize v1, add list of versions with import paths

- v2/client.go
- v2/contacts.go
- v2/device_posture.go
- v2/devices.go
- v2/dns.go
- v2/keys.go
- v2/logging.go
- v2/policyfile.go
- v2/tailnet_settings.go
- v2/users.go
- v2/webhooks.go
In Go, the default assumption is that if a func returns (T, error) and
its error is non-nil, the T value is invalid unless otherwise
documented. (io.Reader is the common example of a documented case
where both results can be valid)
On the flip side, the best practice for funcs returning (T, error) is
to only set one or the other non-nil, lest callers accidentally depend
on T always being non-nil and ossifying the implementation, making it
unable to be refactored later.
Updates #cleanup
> v2: return zero values on error

- v2/README.md
- v2/client.go
- v2/oauth.go
This avoids issues such as attempting to configure OAuth with an unitialized BaseURL.
> v2: unify OAuth configuration with rest of client initialization

- v2/webhooks.go
Add missing event categories for webhook subscription types. These were missing in the initial pass, and imply groupings of events to subscribe to.
Updates https://github.com/tailscale/terraform-provider-tailscale/issues/433
> v2/webhooks: add event categories for webhook subscription type

- v2/oauth.go
The new logic keeps the double slash in https:// as opposed to truncating it to https:/
Updates #cleanup
> v2: fix URL building in oauthConfig

- v2/README.md
- v2/keys.go
- v2/keys_test.go
> v2: add support for listing all keys

- v2/client.go
- v2/contacts.go
- v2/device_posture.go
- v2/devices.go
- v2/dns.go
- v2/keys.go
- v2/logging.go
- v2/policyfile.go
- v2/tailnet_settings.go
- v2/users.go
- v2/webhooks.go
> v2: stop using factored type blocks

- v2/client.go
- v2/policyfile.go
- v2/policyfile_test.go
- v2/tailscale_test.go
This allows clients to know which ETag to provide when updating an ACL.
Updates #119
> v2: return ETag with ACL and raw ACL responses

- v2/devices.go
- v2/devices_test.go
The client doesn't return the values for `tailnetLockError` or `tailnetLockKey`, and these would be great to include, since they're included by default when listing devices anyway.
> Add tailnet lock fields to device structs

- tailscale/client.go
- v2/policyfile.go
This is not an officially supported configuration option, and did not work anyway because the JSON name was misspelled.
Updates tailscale/tailscale#11776
> tailscale,v2: remove ACLDERPNode.InsecureForTests

- v2/devices.go
- v2/devices_test.go
This pull request adds the following features:
- Added a v2 client method to perform the [API call for setting a device name](https://tailscale.com/api#tag/devices/POST/device/{deviceId}/name).
- Added a v2 client method to perform the [API call for retrieving device posture attributes](https://tailscale.com/api#tag/devices/GET/device/{deviceId}/attributes).
- Added a v2 client method to perform the [API call for setting device posture attributes](https://tailscale.com/api#tag/devices/POST/device/{deviceId}/attributes/{attributeKey}).
> Add SetName for Device

- v2/logging.go
- v2/logging_test.go
We recently added support for S3 logstreaming endpoints to our API. This involved adding several new fields on the GET LogstreamConfiguration and PUT LogstreamConfiguration endpoints (and a new destinationType, "s3"), plus a new AWSExternalID resource and two new endpoints related to it.
This commit updates the Go client library to reflect all of these changes.
Updates tailscale/corp#24533
> v2/logging: add support for S3 logstreaming
